name: CI

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Enable Nx Cloud distributed tasks
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm exec playwright install --with-deps
      - uses: nrwl/nx-set-shas@v4

      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      # - run: pnpm exec nx affected -t lint test build
      - run: pnpm exec nx affected -t build --base=master

      # # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # # - run: pnpm exec nx-cloud record -- echo Hello World
      # # When you enable task distribution, run the e2e-ci task instead of e2e
      # - run: pnpm exec nx affected -t lint test build e2e

      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      # - run: pnpm exec nx fix-ci
      # if: always()
